Added License File
aquasecurity/vuln-list pull request #3
Opened 2019-10-11 02:04 UTC by pwrmvspark

LICENSE.md added using MIT license. Please provide feedback if possible. Thanks!

2021-01-21 09:14 UTC, JamieMagee commented
@knqyf263 Is it possible to merge this? Or add an appropriate license? (Since this PR was opened, I can see that aquasecurity repos have moved from the MIT license to the Apache 2.0 license)

2021-09-14 08:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/vuln-list?pullRequest=3) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/vuln-list?pullRequest=3) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/vuln-list?pullRequest=3) it.</sub>

2021-11-26 14:52 UTC, gaby commented
Any plans to merge this? PR has been open for more than 2 years

2021-11-26 14:54 UTC, gaby requested changes

2021-11-26 14:54 UTC, gaby commented on LICENSE
> +Copyright (c) 2019 Danny Park
Shouldn't this be: 

`
Copyright (c) 2019 Aqua Security
`

?

2023-07-17 13:05 UTC, closed without merging